name: ci

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: run tests
        run: npm test
      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
  
  scan:
    runs-on: ubuntu-latest
    needs: [ test ]
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3 
      - name: setup codeql
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: build project
        uses: github/codeql-action/autobuild@v2
      - name: analyze code
        uses: github/codeql-action/analyze@v2

  publish:
    runs-on: ubuntu-latest
    needs: [ test, scan ]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: npm ci
      - name: publish package
        run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}